# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

EAPI=6

# ebuild generated by hackport 0.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit eutils haskell-cabal git-r3

MY_PN="CV"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="OpenCV based machine vision library"
HOMEPAGE="http://aleator.github.com/CV/"
EGIT_REPO_URI="https://github.com/aleator/CV.git"

LICENSE="GPL-2"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE="opencv23 +opencv24"

RDEPEND=">=dev-haskell/binary-0.5:=[profile?]
	>=dev-haskell/bindings-dsl-1.0.14:=[profile?] <dev-haskell/bindings-dsl-1.1:=[profile?]
	>=dev-haskell/carray-0.1.5:=[profile?]
	>=dev-haskell/lazysmallcheck-0.5:=[profile?] <dev-haskell/lazysmallcheck-1:=[profile?]
	>=dev-haskell/mtl-1.1.0:=[profile?]
	>=dev-haskell/mwc-random-0.12.0.0:=[profile?]
	>dev-haskell/parallel-3.1:=[profile?]
	>=dev-haskell/parallel-io-0.3.2:=[profile?] <dev-haskell/parallel-io-0.3.4:=[profile?]
	>=dev-haskell/primitive-0.4.1:=[profile?]
	>=dev-haskell/quickcheck-2.1:2=[profile?]
	dev-haskell/storable-complex:=[profile?]
	>=dev-haskell/storable-tuple-0.0.2:=[profile?] <=dev-haskell/storable-tuple-1:=[profile?]
	>=dev-haskell/vector-0.7.0.1:=[profile?] <dev-haskell/vector-1.1:=[profile?]
	>=dev-lang/ghc-7.4.1:=
	>=media-libs/opencv-2.4
"
DEPEND="${RDEPEND}
	dev-haskell/c2hs
	>=dev-haskell/cabal-1.8
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag opencv23 opencv23) \
		$(cabal_flag opencv24 opencv24)
}
