# Copyright 1999-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.0.0

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="SQL Server client library implemented in Haskell"
HOMEPAGE="https://github.com/mitsuji/mssql-simple#readme"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"

RDEPEND="dev-haskell/hostname:=[profile?]
	>=dev-haskell/ms-tds-0.4:=[profile?] <dev-haskell/ms-tds-0.5:=[profile?]
	dev-haskell/network:=[profile?]
	dev-haskell/text:=[profile?]
	dev-haskell/tls:=[profile?]
	dev-haskell/uuid-types:=[profile?]
	>=dev-lang/ghc-9.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
"
