# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.3.6

CABAL_FEATURES="bin"
inherit git-2 haskell-cabal

DESCRIPTION="Google HTML5 Slide generator"
HOMEPAGE="https://github.com/tanakh/pandoc-html5slide"
EGIT_REPO_URI="https://github.com/karky7/pandoc-html5slide.git"

S="${WORKDIR}/${P}/${PN}"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=""
DEPEND="${RDEPEND}
	>=dev-haskell/blaze-html-0.5
	>=dev-haskell/cabal-1.8
	>=dev-haskell/cmdargs-0.9.5
	>=dev-haskell/data-default-0.5
	>=dev-haskell/hamlet-1.0
	>=dev-haskell/pandoc-1.9
	>=dev-haskell/shakespeare-2.0
	>=dev-haskell/shakespeare-css-1.0
	>=dev-haskell/syb-0.3
	>=dev-haskell/text-0.11
	>=dev-lang/ghc-7.4.1
	>=dev-haskell/highlighting-kate-0.5
"
