# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

EAPI=6

# ebuild generated by hackport 0.5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit eutils haskell-cabal

DESCRIPTION="Portable interface to file locking (flock / LockFileEx)"
HOMEPAGE="https://github.com/takano-akio/filelock"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="public-domain"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-lang/ghc-7.4.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.14.0
"

src_prepare() {
	epatch "${FILESDIR}"/Flock-ghc-7.10.3.patch
	eapply_user
}
