# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.3.3

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Dead simple support for reCAPTCHA on Yesod applications."
HOMEPAGE="https://github.com/meteficha/yesod-recaptcha"
SRC_URI="mirror://hackage/packages/archive/${PN}/${PV}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/conduit-0.5:=[profile?]
		<dev-haskell/conduit-1.1:=[profile?]
		dev-haskell/data-default:=[profile?]
		>=dev-haskell/http-conduit-1.5:=[profile?]
		dev-haskell/http-types:=[profile?]
		>=dev-haskell/lifted-base-0.1:=[profile?]
		dev-haskell/network:=[profile?]
		=dev-haskell/network-info-0.2*:=[profile?]
		dev-haskell/text:=[profile?]
		dev-haskell/wai:=[profile?]
		=dev-haskell/yesod-auth-1.2*:=[profile?]
		=dev-haskell/yesod-core-1.2*:=[profile?]
		=dev-haskell/yesod-form-1.3*:=[profile?]
		>=dev-lang/ghc-6.10.4:="
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-1.8"
