# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5

# ebuild generated by hackport 0.3.2

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal git-2

DESCRIPTION="haskell bindings for memcached"
HOMEPAGE="http://github.com/olegkat/haskell-memcached"
EGIT_REPO_URI="https://github.com/karky7/haskell-memcached.git"

S="${WORKDIR}/${P}/${PN}"

LICENSE="OtherLicense"	#Fixme: "OtherLicense", please fill in manually
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND="dev-haskell/network:=[profile?]
		>=dev-haskell/utf8-light-0.4:=[profile?]
		<dev-haskell/utf8-light-1.0:=[profile?]
		>=dev-lang/ghc-7.6.3:="
DEPEND="${RDEPEND}
		>=dev-haskell/cabal-0"
